package com.example.turinggame;

// Cette classe contient l'ensemble des cartes perforees
// Besoin d'une seule variable de ce type
public class TotaliteDesCartesPerforees {
    private MatriceCarte listeCartesPerf[][] = new MatriceCarte[5][3];

    public TotaliteDesCartesPerforees() {
        this.initCartesPerforees();
    }

    // Retourne l'objet MatriceCarte portant ce numero (1 a 5) situe a cette position (1 a 3), avec sa matrice de trous
    public MatriceCarte get(int numCarte, int position) {
        int n = numCarte-1;
        int pos = position-1;
        return this.listeCartesPerf[n][pos];
    }

    private void initCartesPerforees(){
        // Cartes perforées : 1er chiffre=1/2/3/4/5, 2e=position:1/2/3
        MatriceCarte cp = new MatriceCarte(1,1);
        cp.setOn(9,0);
        cp.setOn(2,1);
        cp.setOn(4,1);
        cp.setOn(5,1);
        cp.setOn(11,2);
        cp.setOn(1,3);
        cp.setOn(4,3);
        cp.setOn(6,3);
        cp.setOn(8,3);
        cp.setOn(9,3);
        cp.setOn(6,4);
        cp.setOn(11,4);
        cp.setOn(4,5);
        cp.setOn(1,6);
        cp.setOn(6,6);
        cp.setOn(7,6);
        cp.setOn(9,6);
        cp.setOn(10,6);
        cp.setOn(9,8);
        cp.setOn(4,9);
        cp.setOn(9,9);
        cp.setOn(2,10);
        cp.setOn(4,10);
        cp.setOn(6,10);
        cp.setOn(6,11);
        listeCartesPerf[0][0] = cp;

        cp = new MatriceCarte(1,2);
        cp.setOn(8,0);
        cp.setOn(10,0);
        cp.setOn(4,1);
        cp.setOn(1,2);
        cp.setOn(2,2);
        cp.setOn(7,2);
        cp.setOn(8,2);
        cp.setOn(5,3);
        cp.setOn(7,4);
        cp.setOn(8,4);
        cp.setOn(10,4);
        cp.setOn(3,5);
        cp.setOn(4,5);
        cp.setOn(10,5);
        cp.setOn(1,6);
        cp.setOn(8,6);
        cp.setOn(1,7);
        cp.setOn(4,7);
        cp.setOn(6,7);
        cp.setOn(11,7);
        cp.setOn(9,8);
        cp.setOn(2,9);
        cp.setOn(6,9);
        cp.setOn(9,9);
        cp.setOn(7,11);
        listeCartesPerf[0][1] = cp;

        cp = new MatriceCarte(1,3);
        cp.setOn(8,0);
        cp.setOn(4,1);
        cp.setOn(10,2);
        cp.setOn(1,3);
        cp.setOn(2,3);
        cp.setOn(4,3);
        cp.setOn(6,3);
        cp.setOn(7,3);
        cp.setOn(4,4);
        cp.setOn(10,4);
        cp.setOn(11,4);
        cp.setOn(0,5);
        cp.setOn(8,5);
        cp.setOn(2,6);
        cp.setOn(3,6);
        cp.setOn(9,7);
        cp.setOn(11,7);
        cp.setOn(3,8);
        cp.setOn(5,8);
        cp.setOn(1,9);
        cp.setOn(5,9);
        cp.setOn(7,10);
        cp.setOn(3,11);
        cp.setOn(4,11);
        cp.setOn(7,11);
        listeCartesPerf[0][2] = cp;

        cp = new MatriceCarte(2,1);
        cp.setOn(9,1);
        cp.setOn(11,1);
        cp.setOn(4,2);
        cp.setOn(6,2);
        cp.setOn(0,3);
        cp.setOn(2,3);
        cp.setOn(10,3);
        cp.setOn(5,4);
        cp.setOn(7,4);
        cp.setOn(8,4);
        cp.setOn(10,4);
        cp.setOn(0,5);
        cp.setOn(1,5);
        cp.setOn(3,5);
        cp.setOn(0,7);
        cp.setOn(4,7);
        cp.setOn(5,7);
        cp.setOn(7,7);
        cp.setOn(10,7);
        cp.setOn(2,8);
        cp.setOn(10,8);
        cp.setOn(5,9);
        cp.setOn(7,9);
        cp.setOn(7,10);
        cp.setOn(9,10);
        listeCartesPerf[1][0] = cp;

        cp = new MatriceCarte(2,2);
        cp.setOn(5,0);
        cp.setOn(2,1);
        cp.setOn(3,1);
        cp.setOn(5,1);
        cp.setOn(9,1);
        cp.setOn(0,3);
        cp.setOn(2,4);
        cp.setOn(4,4);
        cp.setOn(9,4);
        cp.setOn(11,4);
        cp.setOn(0,5);
        cp.setOn(6,5);
        cp.setOn(0,6);
        cp.setOn(3,6);
        cp.setOn(6,6);
        cp.setOn(3,7);
        cp.setOn(8,7);
        cp.setOn(10,7);
        cp.setOn(1,8);
        cp.setOn(6,8);
        cp.setOn(8,8);
        cp.setOn(1,9);
        cp.setOn(3,9);
        cp.setOn(6,10);
        cp.setOn(9,10);
        listeCartesPerf[1][1] = cp;

        cp = new MatriceCarte(2,3);
        cp.setOn(5,0);
        cp.setOn(6,0);
        cp.setOn(9,0);
        cp.setOn(9,1);
        cp.setOn(1,2);
        cp.setOn(4,2);
        cp.setOn(5,2);
        cp.setOn(7,2);
        cp.setOn(11,2);
        cp.setOn(1,4);
        cp.setOn(2,4);
        cp.setOn(6,5);
        cp.setOn(4,6);
        cp.setOn(2,7);
        cp.setOn(4,7);
        cp.setOn(7,7);
        cp.setOn(2,8);
        cp.setOn(9,8);
        cp.setOn(11,8);
        cp.setOn(6,9);
        cp.setOn(2,10);
        cp.setOn(3,10);
        cp.setOn(6,10);
        cp.setOn(8,10);
        cp.setOn(8,11);
        listeCartesPerf[1][2] = cp;

        cp = new MatriceCarte(3,1);
        cp.setOn(3,0);
        cp.setOn(7,1);
        cp.setOn(8,1);
        cp.setOn(10,1);
        cp.setOn(3,2);
        cp.setOn(3,3);
        cp.setOn(7,3);
        cp.setOn(11,3);
        cp.setOn(1,4);
        cp.setOn(5,5);
        cp.setOn(6,5);
        cp.setOn(10,5);
        cp.setOn(11,5);
        cp.setOn(8,6);
        cp.setOn(3,7);
        cp.setOn(6,7);
        cp.setOn(1,8);
        cp.setOn(3,8);
        cp.setOn(8,8);
        cp.setOn(11,8);
        cp.setOn(1,9);
        cp.setOn(6,9);
        cp.setOn(3,11);
        cp.setOn(7,11);
        cp.setOn(8,11);
        listeCartesPerf[2][0] = cp;

        cp = new MatriceCarte(3,2);
        cp.setOn(3,0);
        cp.setOn(4,0);
        cp.setOn(9,0);
        cp.setOn(6,1);
        cp.setOn(6,2);
        cp.setOn(9,2);
        cp.setOn(10,2);
        cp.setOn(2,3);
        cp.setOn(4,3);
        cp.setOn(1,5);
        cp.setOn(2,5);
        cp.setOn(5,5);
        cp.setOn(7,5);
        cp.setOn(11,5);
        cp.setOn(7,6);
        cp.setOn(9,6);
        cp.setOn(2,7);
        cp.setOn(5,7);
        cp.setOn(2,8);
        cp.setOn(4,9);
        cp.setOn(10,9);
        cp.setOn(8,10);
        cp.setOn(3,11);
        cp.setOn(4,11);
        cp.setOn(8,11);
        listeCartesPerf[2][1] = cp;

        cp = new MatriceCarte(3,3);
        cp.setOn(4,0);
        cp.setOn(10,0);
        cp.setOn(10,1);
        cp.setOn(3,2);
        cp.setOn(6,2);
        cp.setOn(8,2);
        cp.setOn(0,3);
        cp.setOn(8,3);
        cp.setOn(3,4);
        cp.setOn(3,5);
        cp.setOn(10,5);
        cp.setOn(11,5);
        cp.setOn(1,6);
        cp.setOn(5,6);
        cp.setOn(6,6);
        cp.setOn(8,7);
        cp.setOn(0,8);
        cp.setOn(1,8);
        cp.setOn(10,8);
        cp.setOn(3,9);
        cp.setOn(4,9);
        cp.setOn(7,9);
        cp.setOn(8,9);
        cp.setOn(10,9);
        cp.setOn(6,11);
        listeCartesPerf[2][2] = cp;

        cp = new MatriceCarte(4,1);
        cp.setOn(4,0);
        cp.setOn(6,0);
        cp.setOn(10,0);
        cp.setOn(6,1);
        cp.setOn(1,2);
        cp.setOn(2,2);
        cp.setOn(9,2);
        cp.setOn(10,2);
        cp.setOn(5,3);
        cp.setOn(0,4);
        cp.setOn(2,4);
        cp.setOn(3,4);
        cp.setOn(8,5);
        cp.setOn(0,6);
        cp.setOn(2,6);
        cp.setOn(3,6);
        cp.setOn(11,6);
        cp.setOn(11,7);
        cp.setOn(0,8);
        cp.setOn(6,8);
        cp.setOn(7,8);
        cp.setOn(3,9);
        cp.setOn(3,10);
        cp.setOn(5,10);
        cp.setOn(8,10);
        listeCartesPerf[3][0] = cp;

        cp = new MatriceCarte(4,2);
        cp.setOn(6,0);
        cp.setOn(7,0);
        cp.setOn(10,1);
        cp.setOn(5,2);
        cp.setOn(1,3);
        cp.setOn(3,3);
        cp.setOn(7,3);
        cp.setOn(8,3);
        cp.setOn(10,3);
        cp.setOn(11,3);
        cp.setOn(1,4);
        cp.setOn(5,4);
        cp.setOn(2,6);
        cp.setOn(5,6);
        cp.setOn(10,6);
        cp.setOn(7,7);
        cp.setOn(0,8);
        cp.setOn(4,8);
        cp.setOn(5,8);
        cp.setOn(7,8);
        cp.setOn(10,8);
        cp.setOn(2,10);
        cp.setOn(4,10);
        cp.setOn(5,10);
        cp.setOn(7,10);
        listeCartesPerf[3][1] = cp;

        cp = new MatriceCarte(4,3);
        cp.setOn(3,0);
        cp.setOn(7,0);
        cp.setOn(5,1);
        cp.setOn(7,1);
        cp.setOn(2,2);
        cp.setOn(9,2);
        cp.setOn(11,3);
        cp.setOn(0,4);
        cp.setOn(5,4);
        cp.setOn(6,4);
        cp.setOn(8,4);
        cp.setOn(9,4);
        cp.setOn(2,5);
        cp.setOn(0,6);
        cp.setOn(7,6);
        cp.setOn(8,6);
        cp.setOn(10,6);
        cp.setOn(0,7);
        cp.setOn(3,7);
        cp.setOn(5,7);
        cp.setOn(10,7);
        cp.setOn(7,8);
        cp.setOn(2,9);
        cp.setOn(9,9);
        cp.setOn(5,11);
        listeCartesPerf[3][2] = cp;

        cp = new MatriceCarte(5,1);
        cp.setOn(5,0);
        cp.setOn(7,0);
        cp.setOn(8,0);
        cp.setOn(3,1);
        cp.setOn(5,2);
        cp.setOn(7,2);
        cp.setOn(8,2);
        cp.setOn(4,4);
        cp.setOn(9,4);
        cp.setOn(2,5);
        cp.setOn(7,5);
        cp.setOn(9,5);
        cp.setOn(4,6);
        cp.setOn(5,6);
        cp.setOn(1,7);
        cp.setOn(2,7);
        cp.setOn(8,7);
        cp.setOn(9,7);
        cp.setOn(4,8);
        cp.setOn(5,8);
        cp.setOn(2,9);
        cp.setOn(8,9);
        cp.setOn(10,9);
        cp.setOn(4,11);
        cp.setOn(5,11);
        listeCartesPerf[4][0] = cp;

        cp = new MatriceCarte(5,2);
        cp.setOn(7,1);
        cp.setOn(8,1);
        cp.setOn(11,1);
        cp.setOn(3,2);
        cp.setOn(4,2);
        cp.setOn(11,2);
        cp.setOn(6,3);
        cp.setOn(9,3);
        cp.setOn(0,4);
        cp.setOn(3,4);
        cp.setOn(6,4);
        cp.setOn(8,5);
        cp.setOn(9,5);
        cp.setOn(4,6);
        cp.setOn(11,6);
        cp.setOn(0,7);
        cp.setOn(9,7);
        cp.setOn(3,8);
        cp.setOn(11,8);
        cp.setOn(5,9);
        cp.setOn(7,9);
        cp.setOn(8,9);
        cp.setOn(3,10);
        cp.setOn(5,11);
        cp.setOn(6,11);
        listeCartesPerf[4][1] = cp;

        cp = new MatriceCarte(5,3);
        cp.setOn(2,1);
        cp.setOn(3,1);
        cp.setOn(6,1);
        cp.setOn(8,1);
        cp.setOn(11,1);
        cp.setOn(3,3);
        cp.setOn(5,3);
        cp.setOn(9,3);
        cp.setOn(10,3);
        cp.setOn(7,4);
        cp.setOn(1,5);
        cp.setOn(4,5);
        cp.setOn(5,5);
        cp.setOn(7,5);
        cp.setOn(9,5);
        cp.setOn(9,6);
        cp.setOn(11,6);
        cp.setOn(1,7);
        cp.setOn(6,7);
        cp.setOn(4,8);
        cp.setOn(6,8);
        cp.setOn(8,8);
        cp.setOn(4,10);
        cp.setOn(5,10);
        cp.setOn(9,10);
        listeCartesPerf[4][2] = cp;
    }
}
